const razorpay = require("../config/razorpay")

exports.createOrder = async (req,res)=>{

const options = {

amount:12500 * 100, // ₹12500 installment
currency:"INR"

}

const order = await razorpay.orders.create(options)

res.json(order)

}
exports.paymentSuccess = async (req,res)=>{

const {studentId,amount} = req.body

const student = await Student.findById(studentId)

student.feePaid += amount

if(student.feePaid >= student.hostelFeeTotal){
student.feeStatus = "Paid"
}

await student.save()

res.json({
message:"Payment Updated"
})

}
const Student = require("../models/Student")

exports.paymentSuccess = async (req,res)=>{

try{

const {studentId,amount} = req.body

const student = await Student.findById(studentId)

if(!student){
return res.status(404).json({message:"Student not found"})
}

student.feePaid = (student.feePaid || 0) + amount

if(student.feePaid >= student.hostelFeeTotal){
student.feeStatus = "Paid"
}else{
student.feeStatus = "Partial"
}

await student.save()

res.json({
message:"Payment Updated",
feePaid:student.feePaid
})

}catch(err){

console.log(err)
res.status(500).json({error:err.message})

}

}
const Payment = require("../models/Payment")


exports.paymentSuccess = async (req,res)=>{

const {studentId,amount,paymentId} = req.body

const student = await Student.findById(studentId)

student.feePaid += amount

if(student.feePaid >= student.hostelFeeTotal){
student.feeStatus = "Paid"
}

await student.save()

// save payment history
const payment = new Payment({

studentId,
amount,
paymentId

})

await payment.save()

res.json({
message:"Payment Recorded"
})

}
exports.getPaymentHistory = async (req,res)=>{

const payments = await Payment
.find({studentId:req.params.id})
.sort({_id:-1})

res.json(payments)

}
const PDFDocument = require("pdfkit")

exports.downloadReceipt = async (req,res)=>{

const payment = await Payment.findById(req.params.id)
.populate("studentId")

const doc = new PDFDocument()

res.setHeader(
"Content-Type",
"application/pdf"
)

doc.text("Hostel Fee Receipt",200,50)

doc.text(`Student: ${payment.studentId.fullName}`,50,150)

doc.text(`Amount: ₹${payment.amount}`,50,180)

doc.text(`Payment ID: ${payment.paymentId}`,50,210)

doc.text(`Date: ${new Date(payment.date).toLocaleDateString()}`,50,240)

doc.pipe(res)

doc.end()

}


exports.getFeeAnalytics = async (req,res)=>{

const students = await Student.find()

let totalStudents = students.length
let totalCollected = 0
let pendingFees = 0

students.forEach(s=>{

totalCollected += s.feePaid || 0

pendingFees += (s.hostelFeeTotal || 25000) - (s.feePaid || 0)

})

res.json({

totalStudents,
totalCollected,
pendingFees

})

}




exports.downloadPendingFeePDF = async (req, res) => {

const students = await Student.find()

const PDFDocument = require("pdfkit")
const doc = new PDFDocument({ margin: 40 })

res.setHeader("Content-Type", "application/pdf")
res.setHeader(
  "Content-Disposition",
  "attachment; filename=pending-fee-report.pdf"
)

doc.pipe(res)

// 🏠 HEADER
doc.fontSize(22).text("🏠 Shubham Hostel", { align: "center" })
doc.moveDown(0.5)
doc.fontSize(16).text("Pending Fee Report", { align: "center" })

doc.moveDown()

doc.fontSize(10).text(`Date: ${new Date().toLocaleDateString()}`, { align: "right" })

doc.moveDown()

let y = 140

// 👉 Function to draw table
const drawTable = (title, data) => {

doc.moveDown()

doc.fontSize(14).fillColor("#000").text(title, 50, y)

y += 20

// Table Header
doc.fontSize(12)
doc.text("No.", 50, y)
doc.text("Name", 90, y)
doc.text("Room", 250, y)
doc.text("Pending Fee", 350, y)

doc.moveTo(50, y + 15).lineTo(550, y + 15).stroke()

y += 25

let total = 0
let count = 1

data.forEach((s) => {

const pending = (s.hostelFeeTotal || 25000) - (s.feePaid || 0)

if (pending > 0) {

  doc.text(count++, 50, y)
  doc.text(s.fullName, 90, y)
  doc.text(s.roomNumber || "-", 250, y)
  doc.text(`₹${pending}`, 350, y)

  y += 20

  if (y > 750) {
    doc.addPage()
    y = 50
  }

  total += pending
}

})

// Section Total
y += 10
doc.fontSize(12).text(`Total ${title}: ₹${total}`, 50, y)

y += 30

return total
}

// 👉 Separate data
const girls = students.filter(s => s.hostelType === "Girls")
const boys = students.filter(s => s.hostelType === "Boys")

// 👉 Draw Girls first
let girlsTotal = drawTable("👧 Girls Hostel", girls)

// 👉 Draw Boys after
let boysTotal = drawTable("👦 Boys Hostel", boys)

// 👉 Grand Total
doc.moveDown()

doc.fontSize(14).text(`Grand Total Pending Fee: ₹${girlsTotal + boysTotal}`, 50, y)

// Footer
doc.fontSize(10).fillColor("gray")
.text("Generated by Hostel Management System", 50, 800, {
  align: "center"
})

doc.end()
}